import { focalFromHfov } from "../core/camera.ts";
import { median } from "../core/math.ts";
import { TRUNK_LANDMARK_FRACTION } from "../fixtures/anthropometry.ts";
import { NECK_ABOVE_STERNUM } from "../layers/l04-pose.ts";
import {
  JOINTS,
  type AnalysisRequest,
  type FrameObservation,
  type Handedness,
  type Joint,
  type PlayerLevel,
  type PlayerProfile,
  type Pose2D,
  type StrokeType,
  type CameraPlacement,
} from "../core/types.ts";
import type { DepthPrior } from "../layers/l06-lift3d.ts";

/**
 * The clip file: how footage that was not generated by the fixtures gets in.
 *
 * The pipeline does not start at pixels. Layer 3 and layer 4 are adapters over
 * a pose estimator, and the estimator itself is deliberately not part of this
 * codebase — it is a large model with its own release cycle, and pinning one
 * inside the measurement chain would make the chain untestable. What the
 * pipeline needs is a per-frame set of 2D joints with detector scores, which
 * every current estimator produces.
 *
 * This module defines that hand-off as a plain JSON file, maps the common
 * keypoint layouts onto the tennis skeleton, and says plainly what is missing
 * when something is missing. Two things beyond the joints matter enough to be
 * part of the format:
 *
 *   - the contact frame, because no bare pose track marks it and every timing
 *     measurement is referenced to it;
 *   - a depth track, because without one the reconstruction cannot resolve the
 *     depth direction and the report will — correctly — decline to quote any
 *     angle. See `MIRROR_RESOLVED` in layer 10.
 */

export const CLIP_FORMAT = "baseline-vision-clip";
export const CLIP_VERSION = 1;

/* ------------------------------------------------------------------ */
/* Keypoint layouts                                                    */
/* ------------------------------------------------------------------ */

/**
 * Keypoint orders of the estimators people actually run, mapped onto the
 * tennis skeleton. `null` means the layout has a point there that this
 * skeleton has no use for — an eye, an ear — not that something is wrong.
 */
export const KEYPOINT_LAYOUTS: Record<string, ReadonlyArray<Joint | null>> = {
  /** COCO-17: the output of YOLO-pose, RTMPose-COCO, OpenPose body_25 subset. */
  coco17: [
    "head", // nose, taken as the head landmark; see `headFromFace`
    null, // left eye
    null, // right eye
    null, // left ear
    null, // right ear
    "shoulderL",
    "shoulderR",
    "elbowL",
    "elbowR",
    "wristL",
    "wristR",
    "hipL",
    "hipR",
    "kneeL",
    "kneeR",
    "ankleL",
    "ankleR",
  ],
  /** Halpe-26: COCO-17 plus head, neck, hip centre and the foot points. */
  halpe26: [
    null, // nose
    null,
    null,
    null,
    null,
    "shoulderL",
    "shoulderR",
    "elbowL",
    "elbowR",
    "wristL",
    "wristR",
    "hipL",
    "hipR",
    "kneeL",
    "kneeR",
    "ankleL",
    "ankleR",
    "head",
    "neck",
    "pelvis",
    "footL", // left big toe
    "footR", // right big toe
    null, // left small toe
    null, // right small toe
    null, // left heel
    null, // right heel
  ],
  /** MediaPipe Pose, 33 landmarks. */
  mediapipe33: [
    "head", // nose
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "shoulderL",
    "shoulderR",
    "elbowL",
    "elbowR",
    "wristL",
    "wristR",
    null, // left pinky
    null, // right pinky
    "handL", // left index
    "handR", // right index
    null, // left thumb
    null, // right thumb
    "hipL",
    "hipR",
    "kneeL",
    "kneeR",
    "ankleL",
    "ankleR",
    null, // left heel
    null, // right heel
    "footL", // left foot index
    "footR", // right foot index
  ],
  /** This project's own 22 joints, in `JOINTS` order. */
  native: JOINTS as ReadonlyArray<Joint>,
};

/* ------------------------------------------------------------------ */
/* The file                                                           */
/* ------------------------------------------------------------------ */

export interface ClipFile {
  format: typeof CLIP_FORMAT;
  version: number;
  video: {
    fps: number;
    /** Rate the scene was captured at; equals `fps` unless the clip is slow motion. */
    captureFps?: number;
    widthPx: number;
    heightPx: number;
    /** Horizontal field of view in degrees, if it is known. Worth finding out. */
    hfovDeg?: number;
  };
  player: {
    id?: string;
    displayName?: string;
    heightCm: number;
    hand: Handedness;
    backhand?: "one_handed" | "two_handed";
    level: PlayerLevel;
    ageYears?: number;
  };
  stroke: StrokeType;
  /** Named layout, or an explicit list of joint names, one per keypoint. */
  keypointLayout: keyof typeof KEYPOINT_LAYOUTS | Array<Joint | null>;
  /** Frame of ball-racket contact, marked by a person. */
  contactFrame?: number;
  hints?: {
    cameraPlacement?: CameraPlacement;
    cameraHeightM?: number;
  };
  frames: ClipFrame[];
  /** Free text recorded in the report; where the clip came from. */
  source?: string;
}

export interface ClipFrame {
  /** Presentation time in seconds. Optional; derived from `fps` when absent. */
  t?: number;
  /**
   * One `[x, y, score]` per keypoint of the layout; `null` where nothing was
   * found. A fourth entry, `1`, marks a point the estimator itself flagged as
   * occluded — it was inferred rather than seen, and layer 6 weights it down.
   */
  keypoints: Array<[number, number, number] | [number, number, number, number] | null>;
  racket?: { grip: [number, number]; head: [number, number]; score?: number };
  ball?: { x: number; y: number; radiusPx?: number; score?: number };
  /**
   * Optional depth from a monocular 3D model, in metres along the camera axis,
   * one entry per keypoint. Either absolute depth or, more commonly, the
   * root-relative z of a lifter's output — see `rootRelativeDepth`.
   */
  depth?: Array<number | null>;
}

export interface ParsedClip {
  request: AnalysisRequest;
  depthPrior?: DepthPrior;
  /** Everything the file left out that the analysis will feel. */
  warnings: string[];
}

export interface ParseOptions {
  /**
   * How to read `frame.depth`: as absolute depth along the camera axis, or as
   * a lifter's root-relative z, which has to be anchored to a distance first.
   */
  depthMode?: "absolute" | "rootRelative";
  /** 1-sigma accuracy of that depth in metres. */
  depthSigmaM?: number;
  /** Detector score below which a keypoint counts as "not seen"; see `MIN_KEYPOINT_SCORE`. */
  minScore?: number;
  seed?: number;
}

/**
 * Score below which a reported keypoint is treated as absent.
 *
 * Some estimators — MediaPipe among them — emit a landmark for every slot in
 * every frame, marking the ones they did not find with a visibility near zero
 * rather than leaving them out. Read literally, an unfound joint arrives as a
 * confident-looking point at the image origin, which drags the whole pose
 * towards the top-left corner and quietly ruins the reconstruction. Dropping
 * them costs coverage, which the report states; keeping them costs the truth.
 */
export const MIN_KEYPOINT_SCORE = 0.15;

/** Published monocular lifters land around 40–60 mm; claiming better is a claim. */
export const DEFAULT_DEPTH_SIGMA_M = 0.055;

/* ------------------------------------------------------------------ */
/* Parsing                                                            */
/* ------------------------------------------------------------------ */

export function parseClip(input: unknown, options: ParseOptions = {}): ParsedClip {
  const clip = input as ClipFile;
  const warnings: string[] = [];

  if (!clip || typeof clip !== "object") throw new Error("Die Clip-Datei ist kein Objekt.");
  if (clip.format !== CLIP_FORMAT) {
    throw new Error(`Unbekanntes Format "${String(clip.format)}"; erwartet "${CLIP_FORMAT}".`);
  }
  if (clip.version !== CLIP_VERSION) {
    throw new Error(`Clip-Version ${String(clip.version)} wird nicht unterstützt (erwartet ${CLIP_VERSION}).`);
  }
  if (!Array.isArray(clip.frames) || clip.frames.length === 0) {
    throw new Error("Die Clip-Datei enthält keine Bilder.");
  }
  if (!clip.video || !clip.video.fps || !clip.video.widthPx || !clip.video.heightPx) {
    throw new Error("video.fps, video.widthPx und video.heightPx sind Pflichtangaben.");
  }
  if (!clip.player || !clip.player.heightCm || !clip.player.hand) {
    throw new Error("player.heightCm und player.hand sind Pflichtangaben — ohne Körpergröße gibt es keinen Maßstab.");
  }

  const layout: ReadonlyArray<Joint | null> = Array.isArray(clip.keypointLayout)
    ? clip.keypointLayout
    : KEYPOINT_LAYOUTS[clip.keypointLayout];
  if (!layout) {
    throw new Error(
      `Unbekanntes Keypoint-Layout "${String(clip.keypointLayout)}". Bekannt sind: ` +
        Object.keys(KEYPOINT_LAYOUTS).join(", ") + ".",
    );
  }

  const fps = clip.video.fps;
  const captureFps = clip.video.captureFps ?? fps;
  const minScore = options.minScore ?? MIN_KEYPOINT_SCORE;
  const kept: Array<Set<Joint>> = [];
  let dropped = 0;
  let offered = 0;
  const frames: FrameObservation[] = clip.frames.map((frame, index) => {
    if (!Array.isArray(frame.keypoints)) {
      throw new Error(`Bild ${index}: keypoints fehlt oder ist keine Liste.`);
    }
    if (frame.keypoints.length !== layout.length) {
      throw new Error(
        `Bild ${index}: ${frame.keypoints.length} Keypoints, das Layout erwartet ${layout.length}.`,
      );
    }
    const pose2d: Pose2D = {};
    const present = new Set<Joint>();
    layout.forEach((joint, k) => {
      if (!joint) return;
      const kp = frame.keypoints[k];
      if (!kp) return;
      offered++;
      const [x, y, score] = kp;
      if (!Number.isFinite(x) || !Number.isFinite(y)) return;
      if (clampScore(score) < minScore) {
        dropped++;
        return;
      }
      pose2d[joint] = { p: { x, y }, score: clampScore(score), occluded: kp[3] === 1 };
      present.add(joint);
    });
    kept.push(present);

    const observation: FrameObservation = {
      index,
      t: frame.t ?? index / fps,
      pose2d,
    };
    if (frame.racket) {
      observation.racket = {
        grip: { x: frame.racket.grip[0], y: frame.racket.grip[1] },
        head: { x: frame.racket.head[0], y: frame.racket.head[1] },
        score: clampScore(frame.racket.score ?? 0.8),
      };
    }
    if (frame.ball) {
      observation.ball = {
        p: { x: frame.ball.x, y: frame.ball.y },
        radiusPx: frame.ball.radiusPx ?? 6,
        score: clampScore(frame.ball.score ?? 0.8),
      };
    }
    return observation;
  });

  const player: PlayerProfile = {
    id: clip.player.id ?? "clip",
    displayName: clip.player.displayName ?? clip.player.id ?? "Spieler",
    heightCm: clip.player.heightCm,
    hand: clip.player.hand,
    backhand: clip.player.backhand ?? "two_handed",
    level: clip.player.level,
    ageYears: clip.player.ageYears,
  };

  const request: AnalysisRequest = {
    video: {
      fps,
      captureFps,
      widthPx: clip.video.widthPx,
      heightPx: clip.video.heightPx,
      durationS: frames.length / fps,
      hfovDeg: clip.video.hfovDeg,
    },
    player,
    stroke: clip.stroke ?? "serve",
    frames,
    hints: {
      cameraPlacement: clip.hints?.cameraPlacement,
      cameraHeightM: clip.hints?.cameraHeightM,
      contactFrame: clip.contactFrame,
    },
    seed: options.seed ?? 42,
  };

  /* --- what the file did not bring ---------------------------------- */

  if (clip.video.hfovDeg === undefined) {
    warnings.push(
      "Keine Brennweite angegeben. Sie wird geschätzt; das vergrößert die Unsicherheit jeder " +
        "Längenangabe. Der Wert steht in den EXIF-Daten der Kamera oder im Datenblatt des Objektivs.",
    );
  }
  if (clip.contactFrame === undefined && !clip.frames.some((f) => f.ball || f.racket)) {
    warnings.push(
      "Weder Treffpunkt markiert noch Ball oder Schläger getrackt. Der Treffpunkt ist der Bezugspunkt " +
        "jeder Zeitmessung — ohne ihn bleiben die meisten Kenngrößen unbestimmt.",
    );
  }
  const feetSeen = frames.some((f) => f.pose2d.footL || f.pose2d.footR);
  if (!feetSeen) {
    warnings.push(
      "Das Keypoint-Layout enthält keine Fußpunkte. Landung und Bodenkontakt lassen sich damit nur " +
        "über die Sprunggelenke abschätzen.",
    );
  }
  if (dropped > offered * 0.2) {
    warnings.push(
      `${Math.round((dropped / Math.max(1, offered)) * 100)} % der gemeldeten Keypoints lagen unter der ` +
        `Score-Schwelle von ${minScore} und wurden als "nicht gesehen" behandelt.`,
    );
  }

  const hasDepth = clip.frames.some((f) => Array.isArray(f.depth));
  if (!hasDepth) {
    warnings.push(
      "Keine Tiefeninformation im Clip. Die Rekonstruktion löst die Tiefenrichtung dann nicht auf, " +
        "und der Bericht wird keine Winkel zitieren. Abhilfe: ein monokulares 3D-Modell " +
        "(MotionBERT, VideoPose3D) über dieselben Bilder laufen lassen und dessen z-Werte mitgeben.",
    );
  }

  const depthPrior = hasDepth ? buildDepthPrior(clip, layout, request, options, warnings, kept) : undefined;

  return { request, depthPrior, warnings };
}

const clampScore = (s: number): number => (Number.isFinite(s) ? Math.max(0, Math.min(1, s)) : 0.5);

/* ------------------------------------------------------------------ */
/* Depth                                                              */
/* ------------------------------------------------------------------ */

/**
 * Turns a lifter's depth track into the prior layer 6 consumes.
 *
 * Absolute depth is used as it stands. Root-relative depth — what a monocular
 * lifter normally emits — has to be anchored to a distance first, and the
 * anchor comes from weak perspective: a segment of known 3D length L that
 * covers p pixels sits at roughly f·L/p. Taking the median over the long,
 * reliably detected segments makes the estimate robust to one bad joint.
 */
function buildDepthPrior(
  clip: ClipFile,
  layout: ReadonlyArray<Joint | null>,
  request: AnalysisRequest,
  options: ParseOptions,
  warnings: string[],
  kept: Array<Set<Joint>>,
): DepthPrior {
  const mode = options.depthMode ?? "rootRelative";
  const sigma = options.depthSigmaM ?? DEFAULT_DEPTH_SIGMA_M;
  const byFrame: Array<Partial<Record<Joint, number>>> = [];

  const focalPx = focalFromHfov(clip.video.hfovDeg ?? 60, clip.video.widthPx);
  if (clip.video.hfovDeg === undefined && mode === "rootRelative") {
    warnings.push(
      "Die Tiefe wurde ohne bekannte Brennweite verankert (Annahme: 60° horizontal). " +
        "Der Abstand zur Kamera ist damit nur grob bestimmt.",
    );
  }

  clip.frames.forEach((frame, index) => {
    const map: Partial<Record<Joint, number>> = {};
    if (!Array.isArray(frame.depth)) {
      byFrame.push(map);
      return;
    }
    const relative: Partial<Record<Joint, number>> = {};
    layout.forEach((joint, k) => {
      if (!joint) return;
      // A depth for a joint the detector did not actually see is the model's
      // guess about a point that is not there.
      if (!kept[index]?.has(joint)) return;
      const z = frame.depth?.[k];
      if (z === null || z === undefined || !Number.isFinite(z)) return;
      relative[joint] = z;
    });

    deriveDepths(relative);

    if (mode === "absolute") {
      byFrame.push(relative);
      return;
    }

    const anchor = anchorDepth(request.frames[index], relative, focalPx, request.player.heightCm / 100);
    if (anchor === null) {
      byFrame.push(map);
      return;
    }
    for (const joint of Object.keys(relative) as Joint[]) {
      map[joint] = anchor + (relative[joint] as number);
    }
    byFrame.push(map);
  });

  const covered = byFrame.filter((m) => Object.keys(m).length > 0).length;
  if (covered < clip.frames.length * 0.8) {
    warnings.push(
      `Tiefeninformation liegt nur für ${Math.round((covered / clip.frames.length) * 100)} % der Bilder vor.`,
    );
  }

  return {
    id: `clip:${mode === "absolute" ? "absolute Tiefe" : "lernbasiert, verankert"}(sigma=${Math.round(sigma * 1000)}mm)`,
    depthM(frameIndex: number, joint: Joint): number | null {
      return byFrame[frameIndex]?.[joint] ?? null;
    },
    sigmaM(): number {
      return sigma;
    },
  };
}

/**
 * Fills in the trunk and hand depths a lifter does not emit.
 *
 * Monocular lifters output the detector's own joint set — shoulders, hips,
 * limbs — and nothing between them. Layer 4 builds pelvis, sternum, neck,
 * spine, thorax and the hand centres from those in the image; their depths have
 * to be built the same way, from the same landmarks, or the reconstruction is
 * handed a skeleton whose root has no depth at all. The root is what the whole
 * depth chain hangs from, so leaving it out costs far more than the small
 * approximation of interpolating it.
 */
function deriveDepths(depths: Partial<Record<Joint, number>>): void {
  const mid = (a: Joint, b: Joint): number | undefined => {
    const za = depths[a];
    const zb = depths[b];
    return za === undefined || zb === undefined ? undefined : (za + zb) / 2;
  };

  const hipMid = mid("hipL", "hipR");
  const shoulderMid = mid("shoulderL", "shoulderR");
  if (depths.pelvis === undefined && hipMid !== undefined) depths.pelvis = hipMid;
  if (depths.sternum === undefined && shoulderMid !== undefined) depths.sternum = shoulderMid;
  if (depths.neck === undefined && shoulderMid !== undefined) {
    depths.neck =
      hipMid === undefined
        ? shoulderMid
        : shoulderMid + (shoulderMid - hipMid) * NECK_ABOVE_STERNUM;
  }
  if (hipMid !== undefined && shoulderMid !== undefined) {
    const lerp = (t: number) => hipMid + (shoulderMid - hipMid) * t;
    if (depths.spine === undefined) depths.spine = lerp(TRUNK_LANDMARK_FRACTION.spine);
    if (depths.thorax === undefined) depths.thorax = lerp(TRUNK_LANDMARK_FRACTION.thorax);
  }
  for (const side of ["L", "R"] as const) {
    const hand = `hand${side}` as Joint;
    const wrist = depths[`wrist${side}` as Joint];
    const elbow = depths[`elbow${side}` as Joint];
    if (depths[hand] === undefined && wrist !== undefined && elbow !== undefined) {
      depths[hand] = wrist + (wrist - elbow) * 0.28;
    }
  }
}

/**
 * Distance from the camera to the player's root, from weak perspective.
 *
 * Uses the segments whose 3D length the lifter itself supplies, so no
 * anthropometric table is needed: the ratio of a segment's metric length to its
 * pixel length is the scale, and the scale times the focal length is the depth.
 */
function anchorDepth(
  frame: FrameObservation | undefined,
  relative: Partial<Record<Joint, number>>,
  focalPx: number,
  heightM: number,
): number | null {
  if (!frame) return null;
  const pairs: Array<[Joint, Joint]> = [
    ["shoulderL", "hipL"],
    ["shoulderR", "hipR"],
    ["hipL", "kneeL"],
    ["hipR", "kneeR"],
    ["kneeL", "ankleL"],
    ["kneeR", "ankleR"],
    ["shoulderL", "shoulderR"],
    ["hipL", "hipR"],
  ];
  const estimates: number[] = [];
  for (const [a, b] of pairs) {
    const pa = frame.pose2d[a];
    const pb = frame.pose2d[b];
    const za = relative[a];
    const zb = relative[b];
    if (!pa || !pb || za === undefined || zb === undefined) continue;
    const px = Math.hypot(pa.p.x - pb.p.x, pa.p.y - pb.p.y);
    if (px < 8) continue;
    // In-plane length of the segment in metres, from the lifter's own 3D:
    // the full 3D length minus the part that runs along the camera axis.
    const full = segmentLengthM(a, b, heightM);
    const along = Math.abs(za - zb);
    const inPlane = Math.sqrt(Math.max(1e-4, full * full - along * along));
    estimates.push((focalPx * inPlane) / px);
  }
  return estimates.length ? (median(estimates) ?? null) : null;
}

/**
 * Segment lengths as fractions of stature, from Winter's anthropometric table.
 * Only the segments `anchorDepth` uses are listed.
 */
const SEGMENT_FRACTION: Record<string, number> = {
  "shoulderL|hipL": 0.288,
  "shoulderR|hipR": 0.288,
  "hipL|kneeL": 0.245,
  "hipR|kneeR": 0.245,
  "kneeL|ankleL": 0.246,
  "kneeR|ankleR": 0.246,
  "shoulderL|shoulderR": 0.259,
  "hipL|hipR": 0.191,
};

const segmentLengthM = (a: Joint, b: Joint, heightM: number): number =>
  (SEGMENT_FRACTION[`${a}|${b}`] ?? 0.25) * heightM;

/* ------------------------------------------------------------------ */
/* Writing                                                            */
/* ------------------------------------------------------------------ */

/**
 * Writes a request back out as a clip file.
 *
 * Used by the round-trip test — a format that cannot reproduce what it read is
 * not a format — and to export a fixture clip as a worked example of the shape
 * a real one has to have.
 */
export function serialiseClip(
  request: AnalysisRequest,
  extra: { contactFrame?: number; source?: string; depth?: Array<Partial<Record<Joint, number>>> } = {},
): ClipFile {
  const layout = KEYPOINT_LAYOUTS.native;
  return {
    format: CLIP_FORMAT,
    version: CLIP_VERSION,
    video: {
      fps: request.video.fps,
      captureFps: request.video.captureFps,
      widthPx: request.video.widthPx,
      heightPx: request.video.heightPx,
      hfovDeg: request.video.hfovDeg,
    },
    player: {
      id: request.player.id,
      displayName: request.player.displayName,
      heightCm: request.player.heightCm,
      hand: request.player.hand,
      backhand: request.player.backhand,
      level: request.player.level,
      ageYears: request.player.ageYears,
    },
    stroke: request.stroke,
    keypointLayout: "native",
    contactFrame: extra.contactFrame ?? request.hints?.contactFrame,
    hints: {
      cameraPlacement: request.hints?.cameraPlacement,
      cameraHeightM: request.hints?.cameraHeightM,
    },
    source: extra.source,
    frames: request.frames.map((frame, index) => {
      const keypoints = layout.map((joint) => {
        const kp = joint ? frame.pose2d[joint] : null;
        if (!kp) return null;
        return (kp.occluded ? [kp.p.x, kp.p.y, kp.score, 1] : [kp.p.x, kp.p.y, kp.score]) as
          | [number, number, number]
          | [number, number, number, number];
      });
      const out: ClipFrame = { t: frame.t, keypoints };
      if (frame.racket) {
        out.racket = {
          grip: [frame.racket.grip.x, frame.racket.grip.y],
          head: [frame.racket.head.x, frame.racket.head.y],
          score: frame.racket.score,
        };
      }
      if (frame.ball) {
        out.ball = {
          x: frame.ball.p.x,
          y: frame.ball.p.y,
          radiusPx: frame.ball.radiusPx,
          score: frame.ball.score,
        };
      }
      const depth = extra.depth?.[index];
      if (depth) {
        out.depth = layout.map((joint) => (joint && depth[joint] !== undefined ? (depth[joint] as number) : null));
      }
      return out;
    }),
  };
}
